spring:
  application:
    name: sample-webflux-http-netty
  main:
    banner-mode: "OFF"

server:
  address: 0.0.0.0
  port: 8080

health:
  path: /health

user:
  timeline:
    path: /api/{user}/timeline
  follow:
    path: /api/{user}/follow
  wall:
    path: /api/{user}/wall